FROM node:22-alpine

WORKDIR /app

# Install minimal Chromium + deps required for Karma
RUN apk update && apk add --no-cache \
    chromium \
    libstdc++ \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont

# Disable GPU etc. for headless Chrome
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_PATH=/usr/lib/chromium/
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .

CMD ["npm", "run", "testCi"]
