name: CI Main

# Trigger
on:
    pull_request:
        branches: ["main","dev"]
        types: [opened, synchronize]

# JOBS
jobs:
    test-front:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Front - Install dependencies
              run: npm -i ci
              working-directory: ./front

            - name: Install Google Chrome
              uses: browser-actions/setup-chrome@v1

            - name: Front - Install and Test
              env:
                CHROME_BIN: /usr/bin/google-chrome-stable
              run: |
                npm run testCi
              working-directory: ./front
    test-back:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Back - Lint
              run: |
                npm run lint
                npm run build
                npm run test
              working-directory: ./back